
POST http://localhost:3000/form
Content-Type: application/json

{
  "name": "John Doe",
  "surname": "John Doe",
  "email": "john.doe@example.com",

  "solectwo": "solectwoA",
  "city": "CityA",
  "street": "StreetA",
  "houseNumber": "1",


  "heatingSource": "pelet",
  "heatingSourcePower": 105,
  "heatingSourceHasGrant": true,
  "heatingSourceGrantYear": 2019,

  "waterHeatingSource": "pompa ciepła",
  "waterHeatingSourcePower": 200,
  "waterHeatingSourceHasGrant": true,
  "waterHeatingSourceGrantYear": 2012,

  "isInterested": true,
  "interestedInYear": 2031
}

######

POST http://localhost:3000/form
Content-Type: application/json

{
  "name": "John Doe",
  "surname": "John Doe",
  "email": "john.doe@example.com",

  "solectwo": "solectwoA",
  "city": "CityA",
  "street": "StreetA",
  "houseNumber": "1",


  "heatingSource": "pelet",
  "heatingSourcePower": 105,
  "heatingSourceHasGrant": true,
  "heatingSourceGrantYear": 2019,

  "waterHeatingSource": "pompa ciepła",
  "waterHeatingSourcePower": 200,
  "waterHeatingSourceHasGrant": false,

  "isInterested": false
}

###

GET http://localhost:3000/submitted_data