
POST http://localhost:3000/form
Content-Type: application/json

{
  "name": "John Doe",
  "surname": "John Doe",
  "email": "john.doe@example.com",

  "solectwo": "solectwoA",
  "city": "CityA",
  "street": "StreetA",
  "houseNumber": "1",


  "heatingSource": "pelet",
  "heatingSourcePower": 105,
  "heatingSourceHasGrant": true,
  "heatingSourceGrantYear": 2019,

  "waterHeatingSource": "pompa ciepła",
  "waterHeatingSourcePower": 200,
  "waterHeatingSourceHasGrant": true,
  "waterHeatingSourceGrantYear": 2012,

  "isInterested": true,
  "interestedInYear": 2031
}

######

POST http://localhost:3000/form
Content-Type: application/json

{"name":"11","surname":"22","email":"33sd4","solectwo":"BABY",
"street":"44","houseNumber":"55","heatingSource":"Pompa ciepła",
"heatingSourcePower":1111,"heatingSourceHasGrant":true,
"heatingSourceGrantYear":2001,"waterHeatingSource":"Piec gazowy",
"waterHeatingSourcePower":2222,"waterHeatingSourceHasGrant":false,
"waterHeatingSourceGrantYear":null,"isInterested":true,
"interestedInYear":2025
}

# {
#   "name": "John Doe",
#   "surname": "John Doe",
#   "email": "john.doe@example4.com",

#   "solectwo": "solectwoA",
#   "street": "StreetA",
#   "houseNumber": "1",


#   "heatingSource": "pelet",
#   "heatingSourcePower": 105,
#   "heatingSourceHasGrant": true,
#   "heatingSourceGrantYear": 2019,

#   "waterHeatingSource": "pompa ciepła",
#   "waterHeatingSourcePower": 200,
#   "waterHeatingSourceHasGrant": false,

#   "isInterested": false
# }

#### 

POST http://localhost:3000/form
Content-Type: application/json

{
  "surname": "John Doe",
  "email": "john.doe@example.com",

  "solectwo": "solectwoA",
  "city": "CityB",
  "street": "StreetC",
  "houseNumber": "1",


  "heatingSource": "pelet",
  "heatingSourcePower": 105,
  "heatingSourceHasGrant": true,
  "heatingSourceGrantYear": 2019,

  "waterHeatingSource": "pompa ciepła",
  "waterHeatingSourcePower": 200,
  "waterHeatingSourceHasGrant": false,

  "isInterested": false
}

###

GET http://localhost:3000/submitted_data

###

GET http://localhost:3000/api/solectwa

###

GET http://localhost:3000/api/streets
Content-Type: application/json

{
  "solectwo": "JAROSTY"
}

####

GET http://localhost:3000/api/streets
Content-Type: application/json

{
  "solectwo": "NIEMA"
}