-- Locations
INSERT INTO "Solectwo" (name) VALUES ('BABY'); ///
INSERT INTO "Solectwo" (name) VALUES ('BIAŁKOWICE');
INSERT INTO "Solectwo" (name) VALUES ('GAJKOWICE');
INSERT INTO "Solectwo" (name) VALUES ('GAZOMIA NOWA');
INSERT INTO "Solectwo" (name) VALUES ('GAZOMIA STARA');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE PIERWSZE');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE DRUGIE');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE DRUGIE - POWĘZINY');
INSERT INTO "Solectwo" (name) VALUES ('JAROSTY');  ///
INSERT INTO "Solectwo" (name) VALUES ('KARLIN');
INSERT INTO "Solectwo" (name) VALUES ('KIEŁCZÓWKA');
INSERT INTO "Solectwo" (name) VALUES ('KOSÓW');
INSERT INTO "Solectwo" (name) VALUES ('MICHAŁÓW');
INSERT INTO "Solectwo" (name) VALUES ('MOSZCZENICA');
INSERT INTO "Solectwo" (name) VALUES ('WOLA MOSZCZENICKA'); xxx
INSERT INTO "Solectwo" (name) VALUES ('PODOLIN');
INSERT INTO "Solectwo" (name) VALUES ('POMYKÓW');
INSERT INTO "Solectwo" (name) VALUES ('RACIBOROWICE');
INSERT INTO "Solectwo" (name) VALUES ('RAKÓW');
INSERT INTO "Solectwo" (name) VALUES ('RĘKORAJ');
INSERT INTO "Solectwo" (name) VALUES ('SIEROSŁAW');
INSERT INTO "Solectwo" (name) VALUES ('SROCK');

-- Streets
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworcowa', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejarzy', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sieradzka', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spacerowa', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sportowa', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Świerkowa', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wąska', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', 1);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zielona', 1);

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejowa', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kwiatowa', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Mariana Grabińskiego', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Miła', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('św. Jana Pawła II', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Turystyczna', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Ustronna', 9);
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Żeńców', 9);

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dolska', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Graniczna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kościelna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krótka', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zbożowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Życzliwa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cmentarna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Główna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krótka', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Parkowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rajska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Batorówka', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Boczna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Główna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Północna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rękorajska', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Strażacka', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Akacjowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cegielniana', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Fiołkowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kwiatowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Modrzewiowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Osiedlowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotra', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Radosna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sezamkowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Tęczowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Topolowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wesoła', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wietrzna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wincentego Witosa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wspólna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zacisze', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('100-lecia Odzyskania Niepodległości', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cegielniana', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cmentarna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworcowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Fabryczna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Hodowlana', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Jaworowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kosowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Lipowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowy Świat', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Poduchowna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Pogodna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rumiankowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spacerowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wesoła', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wrzosowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wschodnia', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Złota', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Akacjowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Boczna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dębowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Gazomska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Jodłowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Klonowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kosowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krzywa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Miodowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Modrzewiowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Ogrodowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Plac im.Teodora Endera', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Plac Włókniarzy', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Projektowana', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Proszeńska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Robotnicza', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rolna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzeczna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Smugowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wiosenna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wiśniowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zaciszna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zielona', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA WOLA'));
