-- Locations
INSERT INTO "Solectwo" (name) VALUES ('Baby');
INSERT INTO "Solectwo" (name) VALUES ('Białkowice');
INSERT INTO "Solectwo" (name) VALUES ('Gajkowice');
INSERT INTO "Solectwo" (name) VALUES ('Gazomia Nowa');
INSERT INTO "Solectwo" (name) VALUES ('Gazomia Stara');
INSERT INTO "Solectwo" (name) VALUES ('Gościmowice Pierwsze');
INSERT INTO "Solectwo" (name) VALUES ('Gościmowice Drugie');
INSERT INTO "Solectwo" (name) VALUES ('Gościmowice Drugie - Powęziny');
INSERT INTO "Solectwo" (name) VALUES ('Jarosty');
INSERT INTO "Solectwo" (name) VALUES ('Karlin');
INSERT INTO "Solectwo" (name) VALUES ('Kiełczówka');
INSERT INTO "Solectwo" (name) VALUES ('Kosów');
INSERT INTO "Solectwo" (name) VALUES ('Michałów');
INSERT INTO "Solectwo" (name) VALUES ('Moszczenica');
INSERT INTO "Solectwo" (name) VALUES ('Wola Moszczenicka');
INSERT INTO "Solectwo" (name) VALUES ('Podolin');
INSERT INTO "Solectwo" (name) VALUES ('Pomyków');
INSERT INTO "Solectwo" (name) VALUES ('Raciborowice');
INSERT INTO "Solectwo" (name) VALUES ('Raków');
INSERT INTO "Solectwo" (name) VALUES ('Rękoraj');
INSERT INTO "Solectwo" (name) VALUES ('Sierosław');
INSERT INTO "Solectwo" (name) VALUES ('Srock');

-- Streets
-- BABY
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworcowa', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejarzy', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sieradzka', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spacerowa', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sportowa', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Świerkowa', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wąska', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zielona', (SELECT id FROM "Solectwo" WHERE name = 'BABY'));

-- GAJKOWICE
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Chmielna', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łódzka', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Poprzeczna', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Północna', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rybacka', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spadowa', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Strażacka', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wąska', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Złota', (SELECT id FROM "Solectwo" WHERE name = 'Gajkowice'));

-- JAROSTY
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejowa', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kwiatowa', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Mariana Grabińskiego', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Miła', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('św. Jana Pawła II', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Turystyczna', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Ustronna', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Żeńców', (SELECT id FROM "Solectwo" WHERE name = 'JAROSTY'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dolska', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Graniczna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kościelna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krótka', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zbożowa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Życzliwa', (SELECT id FROM "Solectwo" WHERE name = 'KARLIN'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cmentarna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Główna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krótka', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Parkowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rajska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', (SELECT id FROM "Solectwo" WHERE name = 'KIEŁCZÓWKA'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Batorówka', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Boczna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Główna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Północna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rękorajska', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Strażacka', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Szkolna', (SELECT id FROM "Solectwo" WHERE name = 'KOSÓW'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Akacjowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cegielniana', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Fiołkowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kwiatowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Modrzewiowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Osiedlowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotra', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Radosna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sezamkowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Tęczowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Topolowa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wesoła', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wietrzna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wincentego Witosa', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wspólna', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zacisze', (SELECT id FROM "Solectwo" WHERE name = 'MICHAŁÓW'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('100-lecia Odzyskania Niepodległości', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cegielniana', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cmentarna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworcowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Fabryczna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Hodowlana', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Jaworowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kolejowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kosowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Lipowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowy Świat', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Poduchowna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Pogodna', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rumiankowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzemieślnicza', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spacerowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wesoła', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wolborska', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wrzosowa', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wschodnia', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Złota', (SELECT id FROM "Solectwo" WHERE name = 'MOSZCZENICA'));

INSERT INTO "Street" ("name", "solectwoId") VALUES ('Akacjowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Boczna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Brzozowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cicha', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dębowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dworska', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Gazomska', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Jodłowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Klonowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Kosowska', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krzywa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Leśna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łąkowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Miodowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Modrzewiowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Nowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Ogrodowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Plac im.Teodora Endera', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Plac Włókniarzy', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Polna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Projektowana', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Proszeńska', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Robotnicza', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rolna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Rzeczna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Smugowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wiosenna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wiśniowa', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zaciszna', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zielona', (SELECT id FROM "Solectwo" WHERE name = 'Wola Moszczenicka'));

-- RAKÓW
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Adama', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Cyprysowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Dębowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Gazomska', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Jarzębinowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Moszczenicka', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Sosnowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Stumilowego Lasu', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Świerkowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wrzosowa', (SELECT id FROM "Solectwo" WHERE name = 'RAKÓW'));

-- SROCK
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Krótka', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łączna', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Łódzka', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Piotrkowska', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Plac Rynek', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Podolska', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Pogodna', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Południowa', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Słoneczna', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Spacerowa', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Stawna', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Wschodnia', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));
INSERT INTO "Street" ("name", "solectwoId") VALUES ('Zielona', (SELECT id FROM "Solectwo" WHERE name = 'SROCK'));