INSERT INTO "Solectwo" (name) VALUES ('BABY');
INSERT INTO "Solectwo" (name) VALUES ('BIAŁKOWICE');
INSERT INTO "Solectwo" (name) VALUES ('GAJKOWICE');
INSERT INTO "Solectwo" (name) VALUES ('GAZOMIA NOWA');
INSERT INTO "Solectwo" (name) VALUES ('GAZOMIA STARA');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE PIERWSZE');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE DRUGIE');
INSERT INTO "Solectwo" (name) VALUES ('GOŚCIMOWICE DRUGIE - POWĘZINY');
INSERT INTO "Solectwo" (name) VALUES ('JAROSTY');
INSERT INTO "Solectwo" (name) VALUES ('KARLIN');
INSERT INTO "Solectwo" (name) VALUES ('KIEŁCZÓWKA');
INSERT INTO "Solectwo" (name) VALUES ('KOSÓW');
INSERT INTO "Solectwo" (name) VALUES ('MICHAŁÓW');
INSERT INTO "Solectwo" (name) VALUES ('MOSZCZENICA');
INSERT INTO "Solectwo" (name) VALUES ('MOSZCZENICA OSIEDLE');
INSERT INTO "Solectwo" (name) VALUES ('MOSZCZENICA WOLA');
INSERT INTO "Solectwo" (name) VALUES ('PODOLIN');
INSERT INTO "Solectwo" (name) VALUES ('POMYKÓW');
INSERT INTO "Solectwo" (name) VALUES ('RACIBOROWICE');
INSERT INTO "Solectwo" (name) VALUES ('RAKÓW');
INSERT INTO "Solectwo" (name) VALUES ('RĘKORAJ');
INSERT INTO "Solectwo" (name) VALUES ('SIEROSŁAW');
INSERT INTO "Solectwo" (name) VALUES ('SROCK');